//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_documents
    {
        public Nullable<System.DateTime> issue_date { get; set; }
        public int valid_by { get; set; }
        public Nullable<int> day_count { get; set; }
        public Nullable<bool> needs_validation { get; set; }
        public string model { get; set; }
        public string number { get; set; }
    }
}
