//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class boring_bar_with_bearing
    {
        public int ID { get; set; }
        public string model_wytaczadła { get; set; }
        public Nullable<int> numer { get; set; }
        public string model_łożyska { get; set; }
        public Nullable<System.DateTime> scrapping_date { get; set; }
    }
}
