//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dokument_wrzeciono
    {
        public int id_dokument_wrzeciono { get; set; }
        public Nullable<System.DateTime> data_wystawienia { get; set; }
        public int termin { get; set; }
        public string uwagi { get; set; }
        public Nullable<int> id_wrzeciono { get; set; }
    
        public virtual wrzeciono wrzeciono { get; set; }
    }
}
