//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lozysko
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lozysko()
        {
            this.wytaczadlo_lozysko = new HashSet<wytaczadlo_lozysko>();
        }
    
        public int id_lozysko { get; set; }
        public string typ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wytaczadlo_lozysko> wytaczadlo_lozysko { get; set; }
    }
}
