//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dokument_wrzeciono> dokument_wrzeciono { get; set; }
        public virtual DbSet<dokument_wytaczadlo> dokument_wytaczadlo { get; set; }
        public virtual DbSet<lozysko> lozysko { get; set; }
        public virtual DbSet<wrzeciono> wrzeciono { get; set; }
        public virtual DbSet<wytaczadlo> wytaczadlo { get; set; }
        public virtual DbSet<wytaczadlo_lozysko> wytaczadlo_lozysko { get; set; }
        public virtual DbSet<wszystkie_dokumenty> wszystkie_dokumenty { get; set; }
        public virtual DbSet<wytaczadlo_z_lozyskiem> wytaczadlo_z_lozyskiem { get; set; }
    }
}
