//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wrzeciono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wrzeciono()
        {
            this.dokument_wrzeciono = new HashSet<dokument_wrzeciono>();
        }
    
        public int id_wrzeciono { get; set; }
        public string typ { get; set; }
        public string nr_seryjny { get; set; }
        public Nullable<System.DateTime> data_zlomowania { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dokument_wrzeciono> dokument_wrzeciono { get; set; }
    }
}
