//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wszystkie_dokumenty
    {
        public Nullable<System.DateTime> data_wystawienia { get; set; }
        public int termin { get; set; }
        public Nullable<int> pozostałe_dni { get; set; }
        public string wymaga_atestu { get; set; }
        public string typ { get; set; }
        public string numer { get; set; }
    }
}
