//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wytaczadlo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wytaczadlo()
        {
            this.dokument_wytaczadlo = new HashSet<dokument_wytaczadlo>();
            this.wytaczadlo_lozysko = new HashSet<wytaczadlo_lozysko>();
        }
    
        public int id_wytaczadlo { get; set; }
        public string typ { get; set; }
        public Nullable<int> nr_rysunku { get; set; }
        public Nullable<System.DateTime> data_zlomowania { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dokument_wytaczadlo> dokument_wytaczadlo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wytaczadlo_lozysko> wytaczadlo_lozysko { get; set; }
    }
}
