//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wytaczadlo_z_lozyskiem
    {
        public int ID { get; set; }
        public string typ_wytaczadła { get; set; }
        public Nullable<int> numer_rysunku { get; set; }
        public string typ_łozyska { get; set; }
        public Nullable<System.DateTime> data_złomowania { get; set; }
    }
}
