//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wytaczadlo_lozysko
    {
        public int id_wytaczadlo_lozysko { get; set; }
        public Nullable<int> id_wytaczadlo { get; set; }
        public Nullable<int> id_lozysko { get; set; }
    
        public virtual lozysko lozysko { get; set; }
        public virtual wytaczadlo wytaczadlo { get; set; }
    }
}
