//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_documents
    {
        public Nullable<System.DateTime> data_wydania { get; set; }
        public int ważne_przez { get; set; }
        public Nullable<int> pozostałe_dni { get; set; }
        public Nullable<bool> wymaga_atestu { get; set; }
        public string model { get; set; }
        public string numer { get; set; }
    }
}
