//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoringSpindlesEntities : DbContext
    {
        public BoringSpindlesEntities()
            : base("name=BoringSpindlesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bearing> bearing { get; set; }
        public virtual DbSet<boring_bar> boring_bar { get; set; }
        public virtual DbSet<boring_bar_bearing> boring_bar_bearing { get; set; }
        public virtual DbSet<document_boring_bar> document_boring_bar { get; set; }
        public virtual DbSet<document_spindle> document_spindle { get; set; }
        public virtual DbSet<spindle> spindle { get; set; }
        public virtual DbSet<all_documents> all_documents { get; set; }
        public virtual DbSet<boring_bar_with_bearing> boring_bar_with_bearing { get; set; }
    }
}
